### ISSUE TITLE
Not working after new dribbble update. 

### ISSUE THREAD

**Issue by gsvineeth** [tylergaw/jribbble#11]
Looks like some API issue.

**Comment by tylergaw** [comment]
@gsvineeth are you using Jribbble 2.x.x? https://github.com/tylergaw/jribbble/releases/tag/v2.0.4

Dribbble finally turned off their legacy API that the original Jribbble was using. So 1.x.x versions of Jribbble will no longer work.

You can find usage examples on http://jribbble.com/

**Comment by tylergaw** [comment]
@gsvineeth I'm gonna go ahead and close this, see my above comment. That's likely what you'd ran into.
