### ISSUE TITLE
Wordpress Issue

### ISSUE THREAD

**Issue by sarahdarr** [tylergaw/jribbble#12]
I am adding your code to my wordpress site and I am getting the following error: Uncaught TypeError: Cannot read property 'setToken' of undefined

Any ideas?

**Comment by tylergaw** [comment]
Hey @sarahdarr, that sounds like maybe the Jribbble file isn't being included or it's being included after you're calling `setToken`.

Can you share the code you're using, that'll help track down the issue.

**Comment by sarahdarr** [comment]
I looked and it appears the files are loading in the right order...Its all on my local machine so I will try and share with you the right pieces...

in functions.php

wp_enqueue_script(
        'vendor',
        get_template_directory_uri() . '/assets/vendors/jribbble.min.js',
        array('jquery')
    );
    // theme scripts
    wp_enqueue_script(
        'theme-init',
        get_template_directory_uri() . '/assets/vendors/custom.js',
        array('jquery')
    );

in my custom.js file

 // NOTE: Don't use this token, replace it with your own client access token.
jQuery.jribbble.setToken('5e15728a7760853de16368503abda24914d48b7d6f0b5515cfdc80032577c59f');

jQuery.jribbble.users('sarahmdarr').shots({per_page: 36}).then(function(shots) {
  var html = [];
  
  shots.forEach(function(shot) {
    html.push('<li class="shots--shot">');
    html.push('<a href="' + shot.html_url + '" target="_blank">');
    html.push('<img src="' + shot.images.normal + '">');
    html.push('</a></li>');
  });
  
  jQuery('.shots').html(html.join(''));
});

**Comment by sarahdarr** [comment]
@tylergaw Any thoughts?

**Comment by tylergaw** [comment]
Hey @sarahdarr, sorry missed your last comment. OK, your JavaScript looks fine. I'm not too familiar with the markup Wordpress outputs from that functions.php, can you share just the rendered html of the page where this needs to be working? Nothin' fancy, just whatever is in view source. I'm just looking for the order of how all the JS is included in the page.

**Comment by sarahdarr** [comment]
@tylergaw No worries. This is not a rush project but would like to have this page done soon.

portfolio.html source 

https://gist.github.com/sarahdarr/3a4b4b1334fde83dcaa0

**Comment by tylergaw** [comment]
@sarahdarr So I'm seeing where jribbble.js is included in there. Does it get packed up with other scripts somehow?

**Comment by tylergaw** [comment]
I'm going to go ahead and close this. See my last comment for where we were.
