### ISSUE TITLE
Search?

### ISSUE THREAD

**Issue by alexiskattan** [tylergaw/jribbble#15]
Love the API! Very cool.  Thank you.

Is there a way to do a search of the site? For example, search for all pictures of "Abraham Lincoln".

**Comment by tylergaw** [comment]
Hey @alexiskattan, there isn't, no. Jribbble is only a JS client for the Dribbble API. That doesn't support text search for shots like that. The only thing it supports is listing shots with a handful of different list types http://developer.dribbble.com/v1/shots/#list-shots or the shots of a user or team.

**Comment by tylergaw** [comment]
I'm gonna go ahead and close this since it's not something we can add in Jribbble without it being added at the Dribbble API level
