### ISSUE TITLE
Does this support the new changes dribbble is doing to its API V2?

### ISSUE THREAD

**Issue by albertocastro** [tylergaw/jribbble#16]
I want to know if this will work with the removal of the client access token and V2 of dribbble API

**Comment by tylergaw** [comment]
@albertocastro In it's current state, likely not. I'm planning on releasing a new version that removes old endpoints that are no longer available in V2.

Also, the big change, is we won't be able to use client access tokens anymore. We'll need to generate Oauth bearer tokens.

I had a short convo with the Dribbble folks here https://twitter.com/tylergaw/status/951438840299958275

My plan is to build a small site to help folks generate access tokens. The effect would be the same as with the client access tokens, but to just give folks that don't know how to do the Oauth handshake some help.

**Comment by tylergaw** [comment]
Hey @albertocastro this should be ready to go now in the 3.0 release https://github.com/tylergaw/jribbble/releases/tag/3.0.0 let me know if you run into any trouble.
