### ISSUE TITLE
Can't show team shots

### ISSUE THREAD

**Issue by srizon** [tylergaw/jribbble#20]
Hi @tylergaw, thanks for updating it to v2. I am wondering if you could help me set it up for team shots?

**Comment by tylergaw** [comment]
Hey @srizon Unfortunately that's no longer possible with Dribbble API v2. They no longer allow getting any team information. The full list of what they support is in their docs https://developer.dribbble.com/v2/

**Comment by srizon** [comment]
That's so sad. I know you had some discussions recently with dribbble api team. Do you know if they have plans to support it near future or removed permanently?

Recently we've created a team website and showing team portfolio from dribbble through jribbble. It was working just fine until api v2 broke the page :(

**Comment by tylergaw** [comment]
Yeah, it's a bummer. It doesn't sound like they plan to support it ever again. But, I'd suggest letting them know at https://twitter.com/dribbbleapi. I've tried contacting them via email/contact form and not got any response. They responded to tweets thought. They also had this survey https://dribbble-feedback.typeform.com/to/hliwT7 asking question about api usage. Might be worth it to do that too.

**Comment by srizon** [comment]
Thanks, man! dribbbleapi just replied to my tweet and they are, it's possible. I'll give it a try with team auth and let you know if that works. https://twitter.com/MamunSrizon/status/985897224457486337

**Comment by tylergaw** [comment]
Oh excellent! OK, yeah if it works out, I'll get that documented in the readme here.

**Comment by srizon** [comment]
Cool! Thank you again. I'll give it a try this weekend and will get back to you if I need any help :) Cheers!

**Comment by srizon** [comment]
Hi @tylergaw, it's me again. Would you mind checking this and let me know what am I doing wrong or any steps that I might have missed? http://creativealiens.com/demo/jribbblev3/

Thanks!

**Comment by tylergaw** [comment]
Hey @srizon yeah, I see it. In the console there's an error:

```
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at (index):16
    at XMLHttpRequest.<anonymous> (jribbble.min.js:2)
```
That's saying that the script is trying to set the `innerHTML` of an element, but that element exist.

In the JS snippet:
```
document.querySelector(".dribbble-shots-list").innerHTML
```

`querySelector` is looking for an element with a class of "dribbble-shots-list". Since it doesn't find one, it returns `null`.

If you add an element to the `body` with that class like `<ul class="dribbble-shots-list"></ul>`, it should start working.

Give that a try.

**Comment by srizon** [comment]
Thanks, @tylergaw! it worked!

**Comment by tylergaw** [comment]
Excellent!
