### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by amiegrrl** [tylergaw/jribbble#21]
Hi Tyler,
I'm updating the feed on my site since the release of the new API. I keep getting the error that something is wrong with the Oauth handshake - triple checked my values from the application & no errors are in the console. I tried resetting the client secret as well. Any help is appreciated - thanks!

**Comment by tylergaw** [comment]
Hey @amiegrrl yeah, should be able to help out. I just had a look at your site here http://amie.design/ does that have the latest code? If so, I see the culprits. There's a few more steps needed to update to Jribbble 3.0

- Grab a 3.0 version of jribbble here https://raw.githubusercontent.com/tylergaw/jribbble/master/dist/jribbble.min.js to replace your current 2.0 jribbble.min.js
- Update the jribbble code in your page.js the way getting shots works has changed a bit in 3.0. There's an example here https://github.com/tylergaw/jribbble#shots that should help you along

Let me know if I'm looking at the wrong code and/or that doesn't work for you.

**Comment by amiegrrl** [comment]
So it turns out I made a silly mistake and that's why the authentication wasn't working - I just had glitch.me for the website URL and callback instead of the application name before it. It was able to get the access token and it is working perfectly now.

Thanks so much for taking a look and for putting together this tool!

**Comment by tylergaw** [comment]
Hey excellent! Glad it's working for you now
