### ISSUE TITLE
How can i limit shots?

### ISSUE THREAD

**Issue by gosteev** [tylergaw/jribbble#22]
Hello. I need the last 6 images from my dribbble page, i tried 
`{token: dribbbleToken, page: 1, per_page: 6}` but seems like it's not working as i thought, because i got all images anyway

**Comment by tylergaw** [comment]
Hey @gosteev do you have a live code example somewhere I could have a look at?

I just tried with page 1 and 6 per_page and it's working for me. Here's a codepen https://codepen.io/tylergaw/pen/a28153977eb3810b8405b9baeab3bb9c/

**Comment by gosteev** [comment]
Yea, my bad, i messed with layout and got wrong init. Thank you!

**Comment by tylergaw** [comment]
Oh cool. OK glad it's working for you. 👍
