### ISSUE TITLE
Popular Function Not Working

### ISSUE THREAD

**Issue by radcatdesign** [tylergaw/jribbble#24]
[Site Link](KYLEMILLERCREATIVE.WEBFLOW.IO
)
(feed in the footer)

It seems to work great for traditional shots, but when I try to bring in popular it breaks and gives me a console error. Here is my code and a screenshot of my error. The error is still present on the live link.

`jribbble.popular({token: "637f6fe822b65aa05a6fc2e91230202a2318716c5d5e7ec4c018b8bfd41af23f",page:1, per_page:48}, function(shotsArray) {
  document.querySelector(".dribbble-shots-list").innerHTML = shotsArray.reduce(function(html, shot) {
    return html + '<li><a href="'+  shot.html_url + '" target="_blank"><img src="' + shot.images.normal + '"></a></li>';
  }, "");
});`

<img src="https://i.ibb.co/Tvnnf4R/Screen-Shot-2019-01-20-at-9-19-48-AM.png" alt="Screen-Shot-2019-01-20-at-9-19-48-AM" border="0">

**Comment by tylergaw** [comment]
I'm gonna go ahead and close this. We ended up chatting over email, but I'll repeat what we discussed there for anyone else that hits this issue in the future:

> The reason popular shots is failing is because that's a special resource in the Dribbble API. It's only available to apps with Dribbble's approval. I forgot I had that in the docs here https://github.com/tylergaw/jribbble#methods-that-will-only-work-with-dribbble-approved-apps and Dribbble has it in their API docs here http://developer.dribbble.com/v2/shots/#list-popular-shots
