### ISSUE TITLE
Cannot retrieve video file

### ISSUE THREAD

**Issue by ghost** [tylergaw/jribbble#25]
Is it possible to retrieve a "video shot"? I noticed Dribbble updated their API allowing for videos: 
http://developer.dribbble.com/v2/shots/#video

**Comment by tylergaw** [comment]
@blazepollard I haven't tried that, but since video shots come back from the same API request, but with an extra key `video` the Jribbble shots method should retrieve video shots the same as any other.

Is it not working for you?
